import asyncio
from playwright.async_api import async_playwright
import os

urls = [
    "http://192.168.1.10/login/verify",
    "https://secure-login-paypal.com/update",
    "http://account-update-apple.com/login",
    "https://amazon-security-alert.net/verify",
    "http://chase-bank-verify-account.com/login",
    "https://netflix-subscription-update.com/payment",
    "http://service-paypal-refund.com/login",
    "https://support-microsoft-alert.com/windows",
    "http://facebook-security-check.com/login",
    "https://instagram-verified-badge.com/login",
    "http://wellsfargo-secure-login.com/account",
    "https://dhl-shipping-tracker.com/login",
    "http://usps-delivery-status.com/update",
    "https://att-email-upgrade.com/login",
    "http://yahoo-mail-security.com/verify",
    "https://linkedin-job-offer.com/login",
    "http://dropbox-file-share.com/login",
    "https://google-docs-secure.com/login",
    "http://office365-password-reset.com/login",
    "https://bankofamerica-secure-alert.com/login"
]

async def capture_screenshots():
    os.makedirs("screenshot", exist_ok=True)
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True)
        page = await browser.new_page(viewport={"width": 1280, "height": 1800})
        
        for i, url in enumerate(urls, 1):
            print(f"Testing {i}/20: {url}")
            await page.goto("http://127.0.0.1:5001")
            
            # Fill the URL and trigger the scan
            await page.fill("#url-input", url)
            await page.click("#scan-btn")
            
            try:
                # Wait for results panel to become visible (it changes display from none to block)
                await page.wait_for_selector("#results-panel", state="visible", timeout=15000)
                
                # Wait for 3 seconds to let CSS animations run (gauge fill) and screenshots load
                await page.wait_for_timeout(3000)
                
                # Take full page screenshot
                filename = f"screenshot/malicious_url_{i:02d}.png"
                
                # We want to make sure the target screenshot generated by Thum.io appears
                await page.wait_for_selector(".screenshot-box", state="visible", timeout=5000)
                # Wait a tiny bit more for it to load background image
                await page.wait_for_timeout(1000)
                
                await page.screenshot(path=filename, full_page=True)
                print(f"Saved {filename}")
            except Exception as e:
                print(f"Failed to scan {url}: {e}")
            
        await browser.close()

asyncio.run(capture_screenshots())
